
[functions.stripe-checkout]
enabled = true
verify_jwt = false
import_map = "./functions/stripe-checkout/deno.json"
entrypoint = "./functions/stripe-checkout/index.ts"

[functions.validate-session]
enabled = true
verify_jwt = false
import_map = "./functions/validate-session/deno.json"
entrypoint = "./functions/validate-session/index.ts"

