

[functions.stripe-checkout]
enabled = true
verify_jwt = false  # Changed to false to allow unauthenticated access for now
import_map = "./functions/stripe-checkout/deno.json"
entrypoint = "./functions/stripe-checkout/index.ts"
headers.Access-Control-Allow-Origin = "*"
headers.Access-Control-Allow-Methods = "POST, GET, OPTIONS"
headers.Access-Control-Allow-Headers = "content-type, authorization, x-client-info, apikey, accept"
headers.Access-Control-Max-Age = "86400"

[functions.validate-session]
enabled = true
verify_jwt = false  # Changed to false to allow unauthenticated access for now
import_map = "./functions/validate-session/deno.json"
entrypoint = "./functions/validate-session/index.ts"
headers.Access-Control-Allow-Origin = "*"
headers.Access-Control-Allow-Methods = "GET, OPTIONS"
headers.Access-Control-Allow-Headers = "content-type, authorization, x-client-info, apikey, accept"
headers.Access-Control-Max-Age = "86400"

