
[functions.stripe-checkout]
enabled = true
verify_jwt = false  # Changed to false to allow unauthenticated access for now
import_map = "./functions/stripe-checkout/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/stripe-checkout/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/stripe-checkout/*.html" ]

# Define CORS headers - note this is now at the same level as the function definition
allowed_origins = ["*", "https://trex-sg.com", "http://localhost:5173"]
allowed_methods = ["GET", "POST", "OPTIONS"]
allowed_headers = ["content-type", "authorization", "accept", "x-client-info"]
expose_headers = ["content-length", "x-kuma-revision"]
max_age = 600
